apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx-svc
  labels:
    service: nginx-service
spec:
  selector:
    service: nginx-pod
  type: NodePort
  ports: 
  - name: http
    port: 80		
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx-pod
  template:
    metadata:
      labels:
        service: nginx-pod
    spec:
      containers:
      - name: nginx-pod
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
